from update_portfolio import PortfolioUpdater
import argparse
import os

def main():
    parser = argparse.ArgumentParser(description="Run the PortfolioPulse investment portfolio update automation.")
    parser.add_argument(
        "--config", 
        type=str, 
        default="config.json", 
        help="Path to the configuration JSON file."
    )
    args = parser.parse_args()

    if not os.path.exists(args.config):
        print(f"Error: Configuration file not found at {args.config}")
        print("Please ensure config.json exists or provide the correct path using --config.")
        print("A dummy config.json can be generated by running update_portfolio.py directly.")
        return

    try:
        updater = PortfolioUpdater(config_path=args.config)
        updater.run_update()
    except FileNotFoundError as e:
        print(f"Configuration error: {e}. Please ensure config.json and credentials.json are correctly set up.")
    except Exception as e:
        print(f"An unexpected error occurred during the update process: {e}")

if __name__ == "__main__":
    main()

